version: 1

honeycomb_team: prod # repo scoped OR could be near the env

deployment_gates:
  staging: # github env name
    queries:
      - honeycomb_environment: catfood # honeycomb env to query against
        spec: '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "status_code",
                  "op": "=",
                  "value": "500"
              }
            ],
            "filter_combination": "AND"
          }'
        threshold:
          operator: <
          value: 1
