version: 1

honeycomb_team: "mridula.jayaraman-gettingstarted"

deployment_gates:
  staging: # github env name
    queries:
      - honeycomb_environment: guide
        spec: '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ]
          }'
        threshold:
          operator: <
          value: 1
